name: basic-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Run Project
        run: dotnet run --project MyBlazorApp
      - name: Run Project Tests
        run: dotnet test MyBlazorAppTests