name: basic-workflow
on: workflow_dispatch
jobs:
  e2e-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Run E2E Tests
        uses: BerniWittmann/background-server-action@1.0.4
        with:
          start: dotnet run --project MyBlazorApp
          wait-on: 'http://localhost:5058'
          command: dotnet test MyBlazorAppTests